### ISSUE TITLE
Developer cannot be verified

### ISSUE THREAD

**Issue by nucliweb** [siiptuo/pio#7]
Hi, I would like to test this tool, but I can't use it 🤷🏽‍♂️

![verified](https://user-images.githubusercontent.com/1307927/87348504-22811b80-c555-11ea-8d35-66d5c81289ed.png)

**Comment by joppuyo** [comment]
Hey,

You can bypass the Gatekeeper error by opening **System Preferences** and selecting **Security and Privacy**. At the bottom, there should be a notification such as "pio was blocked from use because it is not from an identified developer". By clicking "Allow anyway" you should be able to run the app.

**Comment by joppuyo** [comment]
To notarize an app it costs 99$ a year and it's a pain in the ass to set up so unfortunately we'll probably have to live with this for the time being.

Thankfully you have to trust the app once and it'll run without any complaints from then on.

**Comment by nucliweb** [comment]
Thanks a lot @joppuyo , I can use it.
I will send you feedback 😊

**Comment by joppuyo** [comment]
We've added some extra info in the readme how to install pio on the Mac if anyone else runs into this issue in the future 🙂
